apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: test-app
  namespace: flux-system
  annotations:
  image.toolkit.fluxcd.io/insecure-skip-tls-verify: "true"
spec:
  interval: 1m
  image: ghcr.io/algonimbus-trading/test_app
