apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: test-app-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: test-app
  policy:
    semver:
      range: 0.0.X
